### ISSUE TITLE
Preservation of risk table using patchwork

### ISSUE THREAD

**Issue by jayspiegel5** [ddsjoberg/ggsurvfit#1]
Hi there, I am a clinical researcher and I use KM curves for describing overall survival and progression free survival and like the ggsurvfit package, particularly the ability to include risk tables. My issue is that when I try combine OS and PFS plots alongside one another the risk table is not included - this has happened with both patchwork and cowplot.

The code chunks are below:

OS.plt <- ggsurvfit::ggsurvfit(x = fit.srvft,
                     type = "survival",
                     size = 0.75,
                     color = "red")+
  ggsurvfit::add_confidence_interval(fill = "red")+
  ggsurvfit::add_censor_mark(color = "red")+
  ggsurvfit::add_risktable()+
  ggplot2::scale_y_continuous(limits = c(0,1), breaks=seq(from =0, by=0.25))+
  ggplot2::scale_x_continuous( limits = c(0,15),
                              breaks=seq(from=0,
                                to=15,
                                by=3))+
  ggplot2::theme(panel.border = ggplot2::element_blank())+
  ggplot2::theme_minimal()+
  ggplot2::labs(y = "Overall Survival", x = "Months post Infusion")

PFS.plt <- ggsurvfit::ggsurvfit(x = fit.srvft,
                     type = "survival",
                     size = 0.75,
                     color = "red")+
  ggsurvfit::add_confidence_interval(fill = "red")+
  ggsurvfit::add_censor_mark(color = "red")+
  ggsurvfit::add_risktable()+
  ggplot2::scale_y_continuous(limits = c(0,1), breaks=seq(from =0, by=0.25))+
  ggplot2::scale_x_continuous( limits = c(0,15),
                              breaks=seq(from=0,
                                to=15,
                                by=3))+
  ggplot2::theme_minimal()+
  ggplot2::labs(y = "Progression Free Survival", x = "Months post Infusion")

library(patchwork)
OS.plt + PFS.plt

Output:
![image](https://github.com/ddsjoberg/ggsurvfit/assets/125480026/4ece33fe-7bde-46fa-abc6-b46c4e2076b2)

Thanks for your help!

**Comment by ddsjoberg** [comment]
Hi @jayspiegel5 , thanks for the post!

Please take a look at the package website. Does this solve your issue?
https://www.danieldsjoberg.com/ggsurvfit/articles/gallery.html#side-by-side
