### ISSUE TITLE
Changes in PARAM

### ISSUE THREAD

**Issue by ddsjoberg** [ddsjoberg/ggsurvfit#104]
Previous comments from @SHAESEN2
1.  Check if the param/paramcd unique in the data used for estimation. If not, then the programmer forgot to make a subset.
2. If param or paramcd was used as strata then label should default to Time

**Comment by ddsjoberg** [comment]
@SHAESEN2 

PARAM = "The description of the analysis parameter (or time to event endpoint). Example: “Time to Progression”"

Do you have any examples where this is variable can accurately be used as a stratifying variable?

**Comment by SHAESEN2** [comment]
1. I feel it is better to warn the programmer upfront than when its too late (when creating the figure). Many programmers dont have the proper statistical background to understand/see the issue.
2. Yes ADTTE typically contains different time to event parameters (eg time to hopsitalization, time to hospital discharge,...). We often use paramcd as strata to have an overall estimate for each parameter.
