### ISSUE TITLE
Risk table organization - fewest tables as default

### ISSUE THREAD

**Issue by edrill** [ddsjoberg/ggsurvfit#117]
Currently ggsurvfit()'s default risk table for 3 strata is to have 3 individual tables for each strata with fows for "At Risk" and "Events". Would be nice to have the default choose the option that will make the fewest tables, e.g. for 3 strata the default could be 2 tables for "At Risk" and "Events" that include 3 rows each.

**Comment by ddsjoberg** [comment]
I like it! Thanks for the suggestion!
