### ISSUE TITLE
Warning message in `add_risktable_strata_symbol()` forwards user to next warning message

### ISSUE THREAD

**Issue by timtreis** [ddsjoberg/ggsurvfit#129]
When calling `add_risktable_strata_symbol()` on a `ggsurvfit` object, it tells the user to call `add_risktable()` beforehand.

![image](https://user-images.githubusercontent.com/12818242/200290471-32d2570c-31cb-438d-8c7f-e6d3bdda07a1.png)

However, an inexperienced user will just add `+ add_risktable()` to the command, which will inevitably trigger the next warning since it has to be called as `+ add_risktable(risktable_group='risktable_stats')`.

![image](https://user-images.githubusercontent.com/12818242/200290830-b4fc9f45-2485-4305-b710-c6974173d415.png)

This is a tiny bit annoying and could be streamlined, by, for example, just including the required argument in the first thrown warning.

**Comment by ddsjoberg** [comment]
I like the suggestion! We'll get to it soon :)
