### ISSUE TITLE
pkg should export a data frame with labels for columns

### ISSUE THREAD

**Issue by ddsjoberg** [ddsjoberg/ggsurvfit#13]
I added a slightly modified version of `survival::lung` to the package (now includes column labels, factors instead of numeric coding, etc.).

But maybe this should be swapped for something else?

**Comment by ddsjoberg** [comment]
@bailliem did you mention that you have a data set in mind for this? apologies, i didn't write it down in my notes from our meeting.

**Comment by bailliem** [comment]
I'll propose a couple we can review in a PR
