### ISSUE TITLE
Feature request: change color and line type when plotting multiple outcomes

### ISSUE THREAD

**Issue by jiyuxiongdi** [ddsjoberg/ggsurvfit#141]
**Is your feature request related to a problem? Please describe.**
I would like to change the color and line type of the cumulative indicidence and confidence interval for the following plot

```
cuminc(Surv(ttdeath, death_cr) ~ 1, trial) %>%
  ggcuminc(outcome = c("death from cancer", "death other causes")) +
  add_confidence_interval() +
  add_risktable()
```

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ddsjoberg** [comment]
Hi @jiyuxiongdi , thanks for the post.

Can you use the `cuminc()` function with its tidier (https://mskcc-epi-bio.github.io/tidycmprsk/reference/broom_methods_cuminc.html) to create a figure of what you would like to see?

**Comment by ddsjoberg** [comment]
feel free to re-open when you've provided more details, thank you
