### ISSUE TITLE
Feature request: logrank trend test 

### ISSUE THREAD

**Issue by for8ver3** [ddsjoberg/ggsurvfit#153]
suggest with add_pvalue(), add an option to get p-value for trend. 
Similar to the ggsurvplot: test.for.trend

Thanks kindly

**Comment by ddsjoberg** [comment]
Thanks for the post @for8ver3 

Can you please update your post with an example I can run on my machine (both data and code), aka a reprex. Please don't include from ggsurvplot if this is a p-value that can be calculated using the survival package, for example.

**Comment by ddsjoberg** [comment]
Hi @for8ver3 , please feel free to re-open this issue when you have time.

**Comment by for8ver3** [comment]
Hi @ddsjoberg , sorry. Now that I have learnt to use reprex...please see output below. 


``` r
library(reprex)
library(survminer)
#> Loading required package: ggplot2
#> Loading required package: ggpubr
library(survival)
#> 
#> Attaching package: 'survival'
#> The following object is masked from 'package:survminer':
#> 
#>     myeloma
library(ggsurvfit)
data("df_lung")

fit2 <- survfit(Surv(time, status) ~ ph.ecog, df_lung)
ggsurvplot(fit2, df_lung, 
                 risk.table = TRUE, 
                 tables.y.text = F,
                 legend = "none", 
           pval = TRUE,
           test.for.trend = TRUE)
```

![](https://i.imgur.com/cdItnpr.png)

``` r


ggsurvplot(fit2, df_lung, 
           risk.table = TRUE, 
           tables.y.text = F,
           legend = "none", 
           pval = TRUE,
           test.for.trend = FALSE)
```

![](https://i.imgur.com/kKnsSWu.png)

<sup>Created on 2023-08-08 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by ddsjoberg** [comment]
> Please don't include from ggsurvplot 

I'll need more details on how this p-value is calculated.
