### ISSUE TITLE
Add to `theme_ggsurvfit()`

### ISSUE THREAD

**Issue by ddsjoberg** [ddsjoberg/ggsurvfit#4]
Include other themes that may be useful for users (user-contributed?)

**Comment by ddsjoberg** [comment]
- [ ] a theme that exactly replicates the Morris paper
- [ ] a black and white theme

**Comment by ddsjoberg** [comment]
@bailliem regarding these themes:
- Morris theme: We would need to drop a `aes(linetype = strata)` into the aes call in `geom_step()` which occurs in `ggsurvfit()`. This means the user must indicate at that moment when they call `ggsurvfit()` that they want different linetypes, right? 
    - So how do we implement this? Do we add an argument like `ggsurvfit(linetype = TRUE)`, and when it's true we add linetype to the aes? Do we add a general argument like `ggsurvfit()aes_args = list(linetype = strata))`?
- Black and White: to make it black and white we just add a a grey scale. Since it's a scale, we can't just add it to a typical theme. So I don't think we need/should implement a black and white theme.

``` r
library(ggsurvfit)

p <- 
  survfit2(Surv(time, status) ~ sex, data = df_lung) |>
  ggsurvfit() +
  add_confidence_interval(type = "lines")  +
  add_risktable(risktable_group = "risktable_stats") +
  add_risktable_strata_symbol() +
  ggplot2::scale_color_grey()
  
p
```

![](https://i.imgur.com/UGNrlx1.png)

<sup>Created on 2022-08-10 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by bailliem** [comment]
Agree about b/w. I think an example like the one above in a section on styling would be enough. Maybe a figure gallery.

For the other theme I think ggsurvfit(linetype = TRUE) to indicate adding this to aes seems the most elegant way to handle it. I'm not 100 convinced it's worth the effort. I always find using dashed or dotted line types especially with step functions confusing. Add censoring symbols and it gets cluttered.

**Comment by ddsjoberg** [comment]
thanks @bailliem ! added the linetype argument
