### ISSUE TITLE
Add message to user using add_risktable_strata_symbol() when only one stratum 

### ISSUE THREAD

**Issue by bailliem** [ddsjoberg/ggsurvfit#40]
**Is your feature request related to a problem? Please describe.**

A "nice to have" to improve the user experience would be a printed message to indicate that a symbol is not displayed when there is only one stratum i.e. 

```
survfit2(Surv(time, status) ~ 1, data = df_lung) |>
  ggsurvfit() +
  add_risktable()+
  ggplot2::scale_x_continuous() +
  add_risktable_strata_symbol() 
```

ignores the  `add_risktable_strata_symbol() ` call. 

![image](https://user-images.githubusercontent.com/19621679/183873455-8e27a4c6-5be1-4900-a8fe-3bb21e04a533.png)

**Describe the solution you'd like**

In the above scenario a message to the interface would be presented to indicate there is only one stratum therefore a legend is not displayed including symbols to encode strata within the risk table.

**Comment by ddsjoberg** [comment]
Added!

![image](https://user-images.githubusercontent.com/26774684/183914015-56b6d131-5a99-442d-aa83-a6654501a0be.png)
