### ISSUE TITLE
add_risktable_symbol() > Limit the input to a single symbol?

### ISSUE THREAD

**Issue by bailliem** [ddsjoberg/ggsurvfit#41]
This is more a feature than a bug... Leaving this as a ntoe for now. It is possible to add a string arguement as input for the symbol variable using `add_risktable_strata_symbol()` 

```r
survfit2(Surv(time, status) ~ sex, data = df_lung) |>
  ggsurvfit() +
  add_risktable(risktable_group = "risktable_stats")+
  add_risktable_strata_symbol(symbol = "WE CAN PUT ANYTHING IN HERE", vjust = 0.5)
```
![image](https://user-images.githubusercontent.com/19621679/183874936-76c4a493-852c-4437-b341-4078b0ab3369.png)

**Comment by ddsjoberg** [comment]
Hmmm, i am not sure how I could restrict this?

**Comment by bailliem** [comment]
I don't think its worth the effort to restrict. Do you think its worth adding in as an example?

**Comment by ddsjoberg** [comment]
> I don't think its worth the effort to restrict. Do you think its worth adding in as an example?

I am not sure what kind of example you have in mind? But examples are always good! :)

**Comment by ddsjoberg** [comment]
added a note to the documentation indicating that any string can be passed
