### ISSUE TITLE
step ribbon bug

### ISSUE THREAD

**Issue by ddsjoberg** [ddsjoberg/ggsurvfit#50]
@bailliem will fix a bug found in the step ribbon

**Comment by bailliem** [comment]
@ddsjoberg its not an issue with how its set up on ggsurvfit. without loading the package we can still plot and then add to a CI and the step ribbon function is located (see code below). 



```
library(survival)
df_lung <- ggsurvfit::df_lung
p <-
  ggsurvfit::survfit2(Surv(time, status) ~ sex, data = df_lung) |>
  ggsurvfit::ggsurvfit(size = 1) +
  ggsurvfit::add_risktable(risktable_group = "strata")

p + ggsurvfit::add_confidence_interval()
```

**Comment by ddsjoberg** [comment]
@bailliem oh ok, thanks! i didn't follow the first issue closely, and wasn't sure what the underlying issue was
