### ISSUE TITLE
load ggplot2 with ggsurvfit?

### ISSUE THREAD

**Issue by ddsjoberg** [ddsjoberg/ggsurvfit#62]

**Comment by bailliem** [comment]
Probably swaying to yes. I can see the advantage to the user to load ggplot2 from the examples.

**Comment by ddsjoberg** [comment]
> Probably swaying to yes. I can see the advantage to the user to load ggplot2 from the examples. It would be easy to assume it would be available if wanting to customise the plot.

I think for the first release let's now. but i agree, i think it'll be helpful to do so....
