### ISSUE TITLE
Add option to curtail plotting of survival functions based on risk set size

### ISSUE THREAD

**Issue by thomasggodfrey** [ddsjoberg/ggsurvfit#78]
**Is your feature request related to a problem? Please describe.**
Some medical statisticians advise against plotting the survival curve beyond the timepoint at which the risk set becomes unduly small (see example refs below). Definitions for ‘unduly small’ might include:

- The point at which the number of subjects remaining at risk has fallen to below, say, 30 or 10 or 5 (depending on the author recommendations/your CI method/your statistical judgement).
- The point at which the proportion of subjects remaining at risk has fallen to below 10-20% of the original cohort size.
- More complicated schemes (e.g. see Gebski et al).

**Describe the solution you'd like**
It would be good if the user could control the extent to which each survival curve is plotted based on the size of the risk set within that strata. And to be able to apply the constraint (e.g. risk_set_size >= 10) collectively or independently to the different strata/survival curves.  This ought to allow the user to use any method of defining ‘unduly small’, if they can then extract a minimum risk set size from their data to feed into ggsurvfit. The risk table could be constrained to match the longest curve, or be allowed to extend further.

I'm not sure how difficult/possible that would be but it would be a useful innovation. Thanks for all your efforts in developing the package.

**Additional context**
Borgan and Liestol (1990) **A note on confidence intervals and bands for the survival function based on transformations**, Scand J Statist 17: 35-41.
Borgan and Liestol examine how many deaths observed and subjects remaining at risk are required for valid confidence intervals: “a fairly low number of individuals is sufficient to obtain reasonably reliable confidence intervals and bands for the survival function. …/… Considering the confidence intervals, our opinion is that about 10 deaths, and a similar number still at risk, are sufficient for the transformed intervals to perform satisfactorily…”

Pocock et al (2002) **Survival plots of time-to-event outcomes in clinical trials: good practice and pitfalls**, The Lancet, 359 (9318), https://doi.org/10.1016/S0140-6736(02)08594-X
For example, Pocock et al advise: “We recommend that survival plots be halted once the proportion of patients free of an event, but still in follow-up, becomes unduly small. …/… What constitutes “unduly small” is open to debate and depends on the context. It will often be reasonable to curtail the plots when only around 10-20% are still in follow-up”.

Carter and Huang (2009) **Cautionary note regarding the use of CIs obtained from Kaplan-Meier survival curves**. J Clin Oncol. 10;27(2):174-5. https://doi.org/10.1200/JCO.2008.18.8011
Carter and Huang advise: “caution should be exercised in general with both the Kaplan-Meier and Greenwood [standard error] estimators when the risk set is small (say, lower than 30) since they both rely on some asymptotic theory that requires large risk set size".

Gebski et al (2018) **Data maturity and follow-up in time-to-event analyses**, International Journal of Epidemiology, 47(3), https://doi.org/10.1093/ije/dyy013
“We propose two approaches based on the sensitivity index D(t) for deciding when to curtail a Kaplan-Meier plot. Both produce a minimum number remaining at risk required to satisfy a particular criterion. We suggest using these values to decide on a suitable curtailment point in the context of the investigation.”

**Comment by ddsjoberg** [comment]
Hi @thomasggodfrey ! Thanks for the post, and the details! I definitely agree that in most cases we should cut the survival curve short of the longest observation time.

The implementation of your suggestion will be tricky in this package. One of the guiding principles in this package is to write everything as a proper ggplot method, so we can use `+` between all the functions. Another is that we don't touch the default scales (in this case `scale_x_continuous(limits=)` ). We don't touch the scales because ggplot2 scales are not additive, meaning that if we set the limits in one function, then the user needs to modify a scale attribute the original scale will be _replaced_ and any settings added in the original are lost.

These dev principles provide massive flexibility to the users because they can customize the plots using any ggplot2 function or any function from a ggplot extension package. But it does come with some restrictions, like implementing functions liek you've suggested. Also, I am not sure one can combine a data-dependent scale (i.e. setting limits based on the observed data) using `+`?

**Comment by ddsjoberg** [comment]
Will something like this work?

```r
library(ggplot2)

survfit2(Surv(time, status) ~ surg, data = df_colon) |>
  # build Kaplan-Meier plot ----------------------------------------------------
  ggsurvfit(size = 1) +
  add_confidence_interval() +
  # use ggplot2 functions to style the plot and update the labels --------------
  # limit plot to show 8 years and less
  coord_cartesian(xlim = c(0, 8))
```

**Comment by thomasggodfrey** [comment]
Hi Daniel,
Thanks for your comments and feedback on this. I'm more of an R user than developer so can't help with ideas...  thanks for looking into it.

I wonder if this is a related issue:  I am trying to create a KM plot using ggsurvfit, but then add a geom_line() for another curve after the fact. I can add a basic straight line (though just one), but not a complex line.  For example:

Would you expect adding a geom_line to encounter similar plotting issues? Thanks

```
### Example of adding a geom_line to a ggsurvfit plot
# Load packages
library(dplyr)
library(ggplot2)
library(ggsurvfit)

# Estimate survival
km_fit <- survfit2(Surv(time, status) ~ surg, data = df_colon)
  
# Create a basic ggsurvfit plot
p <- km_fit %>%
  ggsurvfit(size = 1) +
  add_confidence_interval() +
  add_risktable() 

#View the plot
p 

# Add some straight lines to test the addition of geom_line()
p + geom_line(aes(x=5))
p + geom_line(aes(y=0.83))
# (this sort of works)


## Fake some data (a stand in for an independent survival curve) from another analysis
# Find the length of data
previous_surv <- data.frame(time = seq(0, max(df_colon$time), by = 1),
                            surv = rep(NA, max(df_colon$time) + 1))

for(i in 1:max(previous_surv$time)){ 
  
  previous_surv$surv[i] <- exp(-i)
  
}

glimpse(previous_surv)

# Try to add a line for this data as a geom
p + geom_line(aes(y = surv, x = time), data = previous_surv)`
```

Error in `.data$monotonicity_type`:
! Column `monotonicity_type` not found in `.data`.
Run `rlang::last_error()` to see where the error occurred.
